### NUMPY

In [3]:
import numpy as n
a = n.array([1, 2, 3, 4])
print(a.dtype)

int32


In [9]:
import numpy as n
a = n.array(["av", "ax23"])
print(a.dtype)
b = n.array(["a.33"])
print(b.dtype)
c = n.array([2.3,4.5])
print(c.dtype)
d = n.array([1+3j])
print(d.dtype)
E = n.array(["is"])
print(E.dtype)

<U4
<U4
float64
complex128
<U2


### Change datatype

In [10]:
import numpy as n
a = n.array([1, 2, 3, 4], dtype = "S")
print(a.dtype)

|S1


In [13]:
import numpy as n
a = n.array([1,2,3],  dtype='i8')
print(a.dtype)

int64


In [18]:
import numpy as n
a = n.array([2.3,4.56], "f4")
print(a.dtype)

float32


In [21]:
import numpy as n
a = n.array(['s', 'jungbook23','222357'], dtype='S')
print(a)
print(a.dtype)

[b's' b'jungbook23' b'222357']
|S10


In [22]:
import numpy as n
a = n.array([1,2,3,4], dtype = "f8")
print(a)
print(a.dtype)

[1. 2. 3. 4.]
float64


### Copy And View

In [23]:
import numpy as n
a = n.array([1,2,3,4])
b = a.copy()
b[0] = 11
print(a)
print(b)

[1 2 3 4]
[11  2  3  4]


In [25]:
import numpy as n
a = n.array([1,2,3,6])
b = a.view()
b[0] = 33
print(a)
print(b)

[33  2  3  6]
[33  2  3  6]


In [27]:
import numpy as n
a = n.array([1,2,3,5], dtype = 'i8')
print(a.dtype)

int64


In [31]:
import numpy as n
a = n.array([[1,2,3,4],[2,3,4,5]])
for x in a:
    for y in x:
        print(y)
    

1
2
3
4
2
3
4
5


In [34]:
import numpy as n

a = n.array([[1,2,3,4], [3,4,5,6]])
for x in a:
    for y in x:
        print(y)
    

1
2
3
4
3
4
5
6


In [36]:
import numpy as n
a = n.array([[2,3,4,5], [5,6,7,8]])
for i, x in n.ndenumerate(a):
    print(i, x)

(0, 0) 2
(0, 1) 3
(0, 2) 4
(0, 3) 5
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [37]:
import numpy as n

a = n.array([[1,2,3],[5,6,7]])
b = n.array([[11,12,13.2],[1.2,5.6,77]])
c = n.concatenate((a, b))
print(c)

[[ 1.   2.   3. ]
 [ 5.   6.   7. ]
 [11.  12.  13.2]
 [ 1.2  5.6 77. ]]


In [ ]:
import numpy as n

a = 