In [ ]:
import numpy as n
a = n.array(16)
print(a.ndim)
print(a)

In [ ]:
import numpy as n
a = n.array([1,2])
print(a)
print(a.ndim)

In [ ]:
import numpy as n
a = n.array([[1,2],[1,2]])
print(a)
print(a.ndim)

In [ ]:
import numpy as a
s= a.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(s)
print(s.ndim)

### Array Indexing

In [ ]:
import numpy as a
n = a.array([[1,2,3,4,5],[10,11,12,4,5]])
print(n)
print(n.ndim)
print(n[0][4])
print(n[1][3])

In [9]:
import numpy as a
n = a.array([[[1,2,3,4,5],[10,11,12,4,5]],[[1,2,3,4,9],[4,5,6,7,11]]])
print(n)
print(n.ndim)
# print(n[0][3])
print(n[1,1,0])

[[[ 1  2  3  4  5]
  [10 11 12  4  5]]

 [[ 1  2  3  4  9]
  [ 4  5  6  7 11]]]
3
4


### Array slicing

In [13]:
import numpy as a
n = a.array([1,2,3,4,5])    
print(n[0:4])
print(n[::-1])
print(n[0:2])
print(n[0:1])

[1 2 3 4]
[5 4 3 2 1]
[1 2]
[1]


In [18]:
import numpy as a
n = a.array([[[1,2,3,4,5],[10,11,12,4,5]],[[1,2,3,4,9],[4,5,6,7,11]]])
print(n[0,1,2:])

[12  4  5]


In [20]:
import numpy as a
n = a.array([[[1,2,3,4,5],[10,11,12,4,5]],[[1,2,3,4,9],[4,5,6,7,11]]])
print(n[1,1,:2])

[4 5]
